name: Android Appium Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted

    env:
      RUNNER_TEMP: /tmp
      RUNNER_TOOL_CACHE: /tmp/toolcache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-appiumlibrary

      - name: Run Appium Tests
        run: |
          robot tests/login-saucelabs.robot
