name: Android Appium Test

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Python Version
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install robotframework
          python3 -m pip install robotframework-appiumlibrary

      - name: Run Appium Tests
        run: |
          python3 -m robot tests/login-saucelabs.robot
